//
// Copyright (C) 1993-1996 Id Software, Inc.
// Copyright (C) 2016-2017 Alexey Khokholov (Nuke.YKT)
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// DESCRIPTION:
//  DOOM main program (D_DoomMain) and game loop (D_DoomLoop),
//  plus functions to determine game mode (shareware, registered),
//  parse command line parameters, configure game parameters (turbo),
//  and call the startup functions.
//

#include <stdlib.h>
#include <dos.h>
//#include <graph.h>
#include <direct.h>
#include <io.h>
#include <fcntl.h>
#include <alloca.h>

#include "doomdef.h"
#include "doomstat.h"

#include "dstrings.h"
#include "sounds.h"


#include "z_zone.h"
#include "w_wad.h"
#include "s_sound.h"
#include "v_video.h"

#include "f_finale.h"
#include "f_wipe.h"

#include "m_misc.h"
#include "m_menu.h"

#include "i_system.h"
#include "i_sound.h"

#include "g_game.h"

#include "hu_stuff.h"
#include "wi_stuff.h"
#include "st_stuff.h"
#include "am_map.h"

#include "p_setup.h"
#include "r_local.h"

#include "d_main.h"
 
#if (EXE_VERSION >= EXE_VERSION_ULTIMATE)
#define BGCOLOR         7
#define FGCOLOR         8
#else
#define BGCOLOR         7
#define FGCOLOR         4
#endif

 
 

//
// D-DoomLoop()
// Not a globally visible function,
//  just included for source reference,
//  called by D_DoomMain, never exits.
// Manages timing and IO,
//  calls all ?_Responder, ?_Ticker, and ?_Drawer,
//  calls I_GetTime,  and I_StartTic
//
void D_DoomLoop (void);


int8_t*           wadfiles[MAXWADFILES];


boolean         nomonsters;     // checkparm of -nomonsters
boolean         respawnparm;    // checkparm of -respawn
boolean         fastparm;       // checkparm of -fast

boolean         drone;

boolean         singletics = false; // debug flag to cancel adaptiveness



extern  uint8_t     sfxVolume;
extern  uint8_t     musicVolume;

extern  boolean inhelpscreens;

skill_t         startskill;
int8_t             startepisode;
int8_t             startmap;
boolean         autostart;

FILE*           debugfile;

boolean         advancedemo;

boolean         modifiedgame;

boolean         shareware;
boolean         registered;
boolean         commercial;
#if (EXE_VERSION >= EXE_VERSION_FINAL)
boolean         plutonia;
boolean         tnt;
#endif


int8_t            wadfile[1024];          // primary wad file
int8_t            basedefault[1024];      // default file


void D_CheckNetGame (void);
void D_ProcessEvents (void);
void G_BuildTiccmd(int8_t index);
//void G_BuildTiccmd (ticcmd_t* cmd);
void D_DoAdvanceDemo (void);


//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
event_t         events[MAXEVENTS];
int8_t             eventhead;
int8_t             eventtail;


//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent (event_t* ev)
{
    events[eventhead] = *ev;
    eventhead = (++eventhead)&(MAXEVENTS-1);
}

//
// D_ProcessEvents
// Send all the events of the given timestamp down the responder chain
//
void D_ProcessEvents (void)
{
    event_t*    ev;
        
    for ( ; eventtail != eventhead ; eventtail = (++eventtail)&(MAXEVENTS-1) ) {
        ev = &events[eventtail];
			if (M_Responder(ev)) {
				continue;               // menu ate the event
		}
		G_Responder (ev);
    }
}

#define MAX_STRINGS 300

uint16_t stringoffsets[MAX_STRINGS];
uint16_t stringbuffersizes[2];

MEMREF		stringRefs[2];

int16_t getStringLength(int16_t stringindex) {
	return  stringoffsets[stringindex + 1] - stringoffsets[stringindex];
}

int8_t* getStringByIndex(int16_t stringindex, int8_t* returndata) {

	uint16_t stringoffset = stringoffsets[stringindex];
	uint16_t length = getStringLength(stringindex);
	int16_t index;
	byte* stringdata;
	if (stringoffset < stringbuffersizes[0]) {
		index = 0;
	} else {
		// todo havent actually tested this..
		index = 1;
		stringoffset -= stringbuffersizes[0];
	}


	stringdata = Z_LoadBytesFromEMS(stringRefs[index]);

		// string ends at the start of the next string...

	memcpy(returndata, &(stringdata[stringoffset]), length);
	// add null terminator?
	returndata[length] = '\0';

	return returndata;
}


void D_InitStrings() {

	// load file
	FILE* handle;
	//filelength_t length;
	int16_t stringlength;
	int8_t* buffer;
	int8_t* lastbuffer;
	int16_t i;
	int16_t j = 0;;
	int16_t laststringoffset;
	int16_t readlength;
	int16_t page = 0;
	int8_t letter;
	int16_t carryover = 0;
	//handle = open("dstrings.txt", O_RDONLY | O_TEXT);
	handle = fopen("dstrings.txt", "r");
	if (handle == NULL) {
		I_Error("strings.txt missing?\n");
		return;
	}
	
	//length = filelength(handle);
	stringoffsets[0] = 0;

	while (1) {
		// break up in pagesize
		
		stringRefs[page] = Z_MallocEMSNew(16384, PU_STATIC, 0, ALLOC_TYPE_STRINGS);
		buffer = Z_LoadBytesFromEMS(stringRefs[page]);

	 
		if (carryover) {
			memcpy(buffer, &lastbuffer[stringoffsets[j]], carryover);
		}

		for (i = 0; i < 16384-carryover; i++) {
			letter = fgetc(handle);
			buffer[i+ carryover] = letter;
			if (letter == 'n') {
				if (buffer[i + carryover - 1] == '\\') {
					// hacky, but oh well.
					buffer[i + carryover - 1] = '\r';
					buffer[i + carryover] = '\n';
				}
			}
			if (letter == '\n') {
				j++;
				stringoffsets[j] = i + (page * 16384);
			
			};

			if (feof(handle)) {
				break;
			}
		}
		stringbuffersizes[page] = stringoffsets[j];
		if (feof(handle)) {
			break;
		}

		page++;
		lastbuffer = buffer;
		
		carryover = i - stringoffsets[j];

	}
	

	fclose(handle);


}



// Fixme. __USE_C_FIXED__ or something.

fixed_t32 FixedMul (fixed_t32	a, fixed_t32 b) {
    // fixed_t_union fp;
    // fp.w = ((long long)a * (long long)b);
    // return fp.h.intbits;
    longlong_union llu;
    fixed_t_union fp;
    llu.l =  ((long long)a * (long long)b);
    fp.h.intbits = llu.h[2];
    fp.h.fracbits = llu.h[1];
    return fp.w;
}
 
fixed_t32 FixedMul1632 (int16_t	a, fixed_t	b) {
    fixed_t_union biga;
	longlong_union llu;
	biga.h.intbits = a;
	biga.h.fracbits = 0;
	llu.l = (biga.w * (long long)b);

	biga.h.intbits = llu.h[2];
	biga.h.fracbits = llu.h[1];
	return biga.w;
}

//
// FixedDiv, C version.
//

//fixed_t32 FixedDivinner(fixed_t32	a, fixed_t32 b int8_t* file, int32_t line)
fixed_t32 FixedDiv (fixed_t32	a, fixed_t32	b) {
	if ((abs(a) >> 14) >= abs(b))
		return (a^b) < 0 ? MINLONG : MAXLONG;
	//return FixedDiv2(a, b, file, line);
	return FixedDiv2(a, b);
}



fixed_t32
FixedDiv2
(fixed_t32	a, fixed_t32	b
	//,int8_t* file, int32_t line
)
{
	// all seem to work, but i think long long is probably the least problematic for 16 bit cpu for now. - sq

	long long c;
	c = ((long long)a << 16) / ((long long)b);


	//float c;
	//c = (((float)a) / ((float)b) * FRACUNIT);
	
	//double c;
	//c = (((double)a) / ((double)b) * FRACUNIT);

	return (fixed_t32) c;
}
//
// D_Display
//  draw current display, possibly wiping it from the previous
//

// wipegamestate can be set to -1 to force a wipe on the next draw
gamestate_t     wipegamestate = GS_DEMOSCREEN;
extern  boolean setsizeneeded;
extern  uint8_t             showMessages;
void R_ExecuteSetViewSize (void);

void D_Display (void)
{
    static  boolean             viewactivestate = false;
    static  boolean             menuactivestate = false;
    static  boolean             inhelpscreensstate = false;
    static  boolean             fullscreen = false;
    static  gamestate_t         oldgamestate = -1;
    static  uint8_t                 borderdrawcount;
	ticcount_t                         nowtime, wipestart;
	int16_t                         tics;
	int16_t                         y;
    boolean                     done;
    boolean                     wipe;
    boolean                     redrawsbar;

    if (nodrawers)
        return;                    // for comparative timing / profiling
                
    redrawsbar = false;
    


    // change the view size if needed
    if (setsizeneeded)
    {
        R_ExecuteSetViewSize ();
        oldgamestate = -1;                      // force background redraw
        borderdrawcount = 3;
    }

#ifdef SKIPWIPE
	wipe = false;
#else
    // save the current screen if about to wipe
    if (gamestate != wipegamestate)
    {
        wipe = true;
        wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
    } else{
        wipe = false;
    }
#endif


    if (gamestate == GS_LEVEL && gametic)
        HU_Erase();

    // do buffered drawing
    switch (gamestate)
    {
      case GS_LEVEL:
        if (!gametic)
            break;
        if (automapactive)
            AM_Drawer ();
        if (wipe || (viewheight != 200 && fullscreen) )
            redrawsbar = true;
        if (inhelpscreensstate && !inhelpscreens)
            redrawsbar = true;              // just put away the help screen
        ST_Drawer (viewheight == 200, redrawsbar );
		fullscreen = viewheight == 200;
        break;

      case GS_INTERMISSION:
        WI_Drawer ();
        break;

      case GS_FINALE:
        F_Drawer ();
        break;

      case GS_DEMOSCREEN:
        D_PageDrawer ();
        break;
    }


    // draw buffered stuff to screen
    I_UpdateNoBlit ();
	// draw the view directly
	if (gamestate == GS_LEVEL && !automapactive && gametic)
        R_RenderPlayerView ();


    if (gamestate == GS_LEVEL && gametic)
        HU_Drawer ();

    // clean up border stuff
	if (gamestate != oldgamestate && gamestate != GS_LEVEL) {
		I_SetPalette(Z_LoadBytesFromEMS(W_CacheLumpNameEMS("PLAYPAL", PU_CACHE)));
	}

    // see if the border needs to be initially drawn
    if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL)
    {
        viewactivestate = false;        // view was not active
        R_FillBackScreen ();    // draw the pattern into the back screen
    }

    // see if the border needs to be updated to the screen
    if (gamestate == GS_LEVEL && !automapactive && scaledviewwidth != 320)
    {
        if (menuactive || menuactivestate || !viewactivestate)
            borderdrawcount = 3;
        if (borderdrawcount)
        {
            R_DrawViewBorder ();    // erase old menu stuff
            borderdrawcount--;
        }

    }

    menuactivestate = menuactive;
    viewactivestate = viewactive;
    inhelpscreensstate = inhelpscreens;
    oldgamestate = wipegamestate = gamestate;

    // draw pause pic
    if (paused)
    {
        if (automapactive)
            y = 4;
        else
            y = viewwindowy+4;
        V_DrawPatchDirect(viewwindowx+(scaledviewwidth-68)/2,
                          y,W_CacheLumpNameEMSAsPatch("M_PAUSE", PU_CACHE));
    }

    // menus go directly to the screen
    M_Drawer ();          // menu is drawn even on top of everything
    NetUpdate ();         // send out any new accumulation


    // normal update
    if (!wipe)
    {
        I_FinishUpdate ();              // page flip or blit buffer
        return;
    }

#ifndef SKIPWIPE

    
    // wipe update
    wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);

    wipestart = ticcount - 1;

    do
    {
        do
        {
            nowtime = ticcount;
            tics = nowtime - wipestart;
        } while (!tics);
        wipestart = nowtime;
        done = wipe_ScreenWipe(wipe_Melt
                               , 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
        I_UpdateNoBlit ();
        M_Drawer ();                            // menu is drawn even on top of wipes
        I_FinishUpdate ();                      // page flip or blit buffer
    } while (!done);
#endif
}



//
//  D_DoomLoop
//
extern  boolean         demorecording;


void D_DoomLoop (void)
{
	// debugging stuff i need to find mem leaks...
//    int8_t result[3000];
//	int8_t result2[2000];
	int32_t lasttick = 0;
	int32_t lastindex = 0;
	int32_t stoptic;
	int32_t linenumber;
    sector_t sector;
	//int32_t i = 0;

	//plat_t* plat;
    if (demorecording)
        G_BeginRecording ();
                
 

    I_InitGraphics ();

    while (1)
    {
        // process one or more tics
        if (singletics) {
			I_StartTic ();
			D_ProcessEvents ();
			G_BuildTiccmd(maketic % BACKUPTICS);
			if (advancedemo) {
				D_DoAdvanceDemo();
			}

			M_Ticker ();

			G_Ticker ();

			gametic++;
            maketic++;

		}
        else
        {
            TryRunTics (); // will run at least one tic
        }
		S_UpdateSounds (players.moRef);// move positional sounds
        // Update display, next frame, with current state.

		 
		D_Display ();

		//SAVEDUNIT = Z_LoadBytesFromEMS(players.moRef);
	
		/*
		if (gametic == 5) {
			memcpy(&copynode, &sectors, numsectors * sizeof(sector_t));
		} else {


		}

		if (gametic > 5) {
			if (memcmp(&copynode, &sectors, numsectors * sizeof(sector_t))) {  //46240
				I_Error("badcopy %i %i", gametic, numsectors * sizeof(sector_t));
			}

		}*/
		/*
		stoptic = 23735;
		if (gametic > stoptic) {
			
			if (gametic != lasttick) {
				lasttick = gametic;
				
				//sprintf(result2, "%i %i %i \n", gametic, prndindex, SAV);

				//SAVEDUNIT = Z_LoadBytesFromEMS(1523);
				SAVEDUNIT = Z_LoadBytesFromEMS(players.moRef);
				 
				sector = ((sector_t*)Z_LoadBytesFromConventional(sectorsRef))[SAVEDUNIT->secnum];

				sprintf(result2, "%i %i %i %i %i %i %i %i %i %i \n", gametic, prndindex, SAVEDUNIT->z >> (16-SHORTFLOORBITS), SAVEDUNIT->floorz, SAVEDUNIT->ceilingz  , SAVEDUNIT->secnum, sector.floorheight, sector.ceilingheight, 0, SAVEDUNIT->type);
				strcat(result, result2);
				

				// frame 140: prnd index different
				// thing 319?


				//doorunit = (vldoor_t*)Z_LoadBytesFromEMS(784);

				//lastindex = prndindex;


			}
		}

		if (gametic == stoptic + 25) {
			I_Error(result);
			//nodes = (byte*)Z_LoadBytesFromEMS(nodesRef);
			//memcpy(copynode, nodes, 46240);
			//if (memcmp(copynode, nodes, 46240)) {  //46240
			//	I_Error("badcopy");
			//}
		}
		*/
	}
}



//
//  DEMO LOOP
//
int8_t             demosequence;
int16_t             pagetic;
int8_t                    *pagename;


//
// D_PageTicker
// Handles timing for warped projection
//
void D_PageTicker (void)
{
    if (--pagetic < 0)
        D_AdvanceDemo ();
}



//
// D_PageDrawer
//
void D_PageDrawer (void)
{
	 V_DrawFullscreenPatch(pagename);
}


//
// D_AdvanceDemo
// Called after each demo or intro demosequence finishes
//
void D_AdvanceDemo (void)
{
    advancedemo = true;
}


//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
 void D_DoAdvanceDemo (void)
{
    players.playerstate = PST_LIVE;  // not reborn
    advancedemo = false;
    usergame = false;               // no save / end game here
    paused = false;
    gameaction = ga_nothing;

#if (EXE_VERSION == EXE_VERSION_ULTIMATE) || (EXE_VERSION == EXE_VERSION_FINAL)
    demosequence = (demosequence+1)%7;
#else
    demosequence = (demosequence+1)%6;
#endif
    
    switch (demosequence)
    {
      case 0:
        if ( commercial )
            pagetic = 35 * 11;
        else
            pagetic = 170;
        gamestate = GS_DEMOSCREEN;
        pagename = "TITLEPIC"; 
        if ( commercial )
          S_StartMusic(mus_dm2ttl);
        else
          S_StartMusic (mus_intro);
        break;
      case 1:
        G_DeferedPlayDemo ("demo1");
        break;
      case 2:
        pagetic = 200;
        gamestate = GS_DEMOSCREEN;
        pagename = "CREDIT";
        break;
      case 3:
        G_DeferedPlayDemo ("demo2");
        break;
      case 4:
        gamestate = GS_DEMOSCREEN;
        if ( commercial)
        {
            pagetic = 35 * 11;
            pagename = "TITLEPIC";
            S_StartMusic(mus_dm2ttl);
        }
        else
        {
            pagetic = 200;
#if (EXE_VERSION >= EXE_VERSION_ULTIMATE)
            pagename = "CREDIT";
#else
            pagename = "HELP2";
#endif
        }
        break;
      case 5:
        G_DeferedPlayDemo ("demo3");
        break;
#if (EXE_VERSION >= EXE_VERSION_ULTIMATE)
        // THE DEFINITIVE DOOM Special Edition demo
      case 6:
        G_DeferedPlayDemo ("demo4");
        break;
#endif
    }
}



//
// D_StartTitle
//
void D_StartTitle (void)
{
    gameaction = ga_nothing;
    demosequence = -1;
    D_AdvanceDemo ();
}

//
// D_GetCursorColumn
//
int16_t D_GetCursorColumn(void)
{
    union REGS regs;

    regs.h.ah = 3;
    regs.h.bh = 0;
    intx86(0x10, &regs, &regs);

    return regs.h.dl;
}

//
// D_GetCursorRow
//
int16_t D_GetCursorRow(void)
{
    union REGS regs;

    regs.h.ah = 3;
    regs.h.bh = 0;
    intx86(0x10, &regs, &regs);

    return regs.h.dh;
}

//
// D_SetCursorPosition
//
void D_SetCursorPosition(int16_t column, int16_t row)
{
    union REGS regs;

    regs.h.dh = row;
    regs.h.dl = column;
    regs.h.ah = 2;
    regs.h.bh = 0;
    intx86(0x10, &regs, &regs);
}

//
// D_DrawTitle
//
void D_DrawTitle(int8_t *string, uint8_t fc, uint8_t bc)
{
    union REGS regs;
    byte color;
	int16_t column;
	int16_t row;
	int16_t i;

    //Calculate text color
    color = (bc << 4) | fc;

    //Get column position
    column = D_GetCursorColumn();

    //Get row position
    row = D_GetCursorRow();

    for (i = 0; i < strlen(string); i++)
    {
        //Set character
        regs.h.ah = 9;
        regs.h.al = string[i];
        regs.w.cx = 1;
        regs.h.bl = color;
        regs.h.bh = 0;
        intx86(0x10, &regs, &regs);

        //Check cursor position
        if (++column > 79)
            column = 0;

        //Set position
        D_SetCursorPosition(column, row);
    }
}


//      print title for every printed line
int8_t            title[128];

//
// D_RedrawTitle
//
void D_RedrawTitle(void)
{
	int16_t column;
	int16_t row;

    //Get current cursor pos
    column = D_GetCursorColumn();
    row = D_GetCursorRow();

    //Set cursor pos to zero
    D_SetCursorPosition(0, 0);

    //Draw title
    D_DrawTitle(title, FGCOLOR, BGCOLOR);

    //Restore old cursor pos
    D_SetCursorPosition(column, row);
}

//
// D_AddFile
//
void D_AddFile (int8_t *file)
{
	int8_t     numwadfiles;
	int8_t    *newfile;
        
    for (numwadfiles = 0 ; wadfiles[numwadfiles] ; numwadfiles++)
        ;

    newfile = malloc (strlen(file)+1);
    strcpy (newfile, file);
        
    wadfiles[numwadfiles] = newfile;
}

//
// IdentifyVersion
// Checks availability of IWAD files by name,
// to determine whether registered/commercial features
// should be executed (notably loading PWAD's).
//
void IdentifyVersion (void)
{
    strcpy(basedefault,"default.cfg");
	 

 

    if ( !access ("doom2.wad",R_OK) )
    {
        commercial = true;
        D_AddFile ("doom2.wad");
        return;
    }

#if (EXE_VERSION >= EXE_VERSION_FINAL)
    if ( !access ("plutonia.wad", R_OK ) )
    {
      commercial = true;
      plutonia = true;
      D_AddFile ("plutonia.wad");
      return;
    }

    if ( !access ( "tnt.wad", R_OK ) )
    {
      commercial = true;
      tnt = true;
      D_AddFile ("tnt.wad");
      return;
    }
#endif

    if ( !access ("doom.wad",R_OK) )
    {
      registered = true;
      D_AddFile ("doom.wad");
      return;
    }

    if ( !access ("doom1.wad",R_OK) )
    {
      shareware = true;
      D_AddFile ("doom1.wad");
      return;
    }

    printf("Game mode indeterminate.\n");
    exit(1);
    //I_Error ("Game mode indeterminate\n");
} 

//
// D_DoomMain
//
void D_DoomMain(void)
{
	int16_t             p;
	int8_t                    file[256];
	union REGS regs;
	int8_t*          textbuffer;

	// Removed
	//FindResponseFile ();

	IdentifyVersion();

	setbuf(stdout, NULL);
	modifiedgame = false;

	nomonsters = M_CheckParm("-nomonsters");
	respawnparm = M_CheckParm("-respawn");
	fastparm = M_CheckParm("-fast");

#ifdef DEBUG_PRINTING

	if (!commercial)
	{
#if (EXE_VERSION >= EXE_VERSION_ULTIMATE)
		sprintf(title,
			"                         "
			"The Ultimate DOOM Startup v%i.%i"
			"                        ",
			VERSION / 100, VERSION % 100);
#else
		sprintf(title,
			"                          "
			"DOOM System Startup v%i.%i"
			"                          ",
			VERSION / 100, VERSION % 100);
#endif
	}
	else
	{
#if (EXE_VERSION >= EXE_VERSION_FINAL)
		if (plutonia)
		{
			sprintf(title,
				"                   "
				"DOOM 2: Plutonia Experiment v%i.%i"
				"                           ",
				VERSION / 100, VERSION % 100);
		}
		else if (tnt)
		{
			sprintf(title,
				"                     "
				"DOOM 2: TNT - Evilution v%i.%i"
				"                           ",
				VERSION / 100, VERSION % 100);
		}
		else
		{
			sprintf(title,
				"                         "
				"DOOM 2: Hell on Earth v%i.%i"
				"                           ",
				VERSION / 100, VERSION % 100);
		}
#else
		sprintf(title,
			"                         "
			"DOOM 2: Hell on Earth v%i.%i"
			"                           ",
			VERSION / 100, VERSION % 100);
#endif
	}

	regs.w.ax = 3;
	intx86(0x10, &regs, &regs);
	D_DrawTitle(title, FGCOLOR, BGCOLOR);

	printf("\nP_Init: Checking cmd-line parameters...\n");
#endif


	// turbo option
	if ((p = M_CheckParm("-turbo")))
	{
		int16_t     scale = 200;
		extern int16_t forwardmove[2];
		extern int16_t sidemove[2];

		if (p < myargc - 1)
			scale = atoi(myargv[p + 1]);
		if (scale < 10)
			scale = 10;
		if (scale > 400)
			scale = 400;
#ifdef DEBUG_PRINTING
		printf("turbo scale: %i%%\n", scale);
#endif
		forwardmove[0] = forwardmove[0] * scale / 100;
		forwardmove[1] = forwardmove[1] * scale / 100;
		sidemove[0] = sidemove[0] * scale / 100;
		sidemove[1] = sidemove[1] * scale / 100;
	}


	p = M_CheckParm("-file");
	if (p)
	{
		// the parms after p are wadfile/lump names,
		// until end of parms or another - preceded parm
		modifiedgame = true;            // homebrew levels
		while (++p != myargc && myargv[p][0] != '-')
			D_AddFile(myargv[p]);
	}

	p = M_CheckParm("-playdemo");

	if (!p)
		p = M_CheckParm("-timedemo");

	if (p && p < myargc - 1)
	{
		sprintf(file, "%s.lmp", myargv[p + 1]);
		D_AddFile(file);
#ifdef DEBUG_PRINTING
		printf("Playing demo %s.lmp.\n", myargv[p + 1]);
#endif
	}

	// get skill / episode / map from parms
	startskill = sk_medium;
	startepisode = 1;
	startmap = 1;
	autostart = false;


	p = M_CheckParm("-skill");
	if (p && p < myargc - 1)
	{
		startskill = myargv[p + 1][0] - '1';
		autostart = true;
	}

	p = M_CheckParm("-episode");
	if (p && p < myargc - 1)
	{
		startepisode = myargv[p + 1][0] - '0';
		startmap = 1;
		autostart = true;
	}


	p = M_CheckParm("-warp");
	if (p && p < myargc - 1)
	{
		if (commercial)
			startmap = atoi(myargv[p + 1]);
		else
		{
			startepisode = myargv[p + 1][0] - '0';
			startmap = myargv[p + 2][0] - '0';
		}
		autostart = true;
	}

	// init subsystems

#ifdef DEBUG_PRINTING
	printf("V_Init: allocate screens.\n");
#endif
	V_Init();

#ifdef DEBUG_PRINTING
	printf("M_LoadDefaults: Load system defaults.\n");
#endif
	M_LoadDefaults();              // load before initing other systems

#ifdef DEBUG_PRINTING
	printf("Z_InitEMS: Init EMS memory allocation daemon. \n");
#endif
	Z_InitEMS();


#ifdef DEBUG_PRINTING
	printf("W_Init: Init WADfiles.\n");
#endif
	W_InitMultipleFiles(wadfiles);

	Z_InitConventional(); // wad loading using a lot of conventional, so do this after..

	// init subsystems
#ifdef DEBUG_PRINTING
	printf("D_InitStrings: loading text.\n");
#endif
	D_InitStrings();

	// Check for -file in shareware
#ifdef CHECK_FOR_ERRORS
	if (modifiedgame) {
		// These are the lumps that will be checked in IWAD,
		// if any one is not present, execution will be aborted.
		int8_t name[23][8]=
		{
			"e2m1","e2m2","e2m3","e2m4","e2m5","e2m6","e2m7","e2m8","e2m9",
			"e3m1","e3m3","e3m3","e3m4","e3m5","e3m6","e3m7","e3m8","e3m9",
			"dphoof","bfgga0","heada1","cybra1","spida1d1"
		};
		int8_t i;

		if (shareware)
			I_Error("\nYou cannot -file with the shareware "
					"version. Register!");

					// Check for fake IWAD with right name,
					// but w/o all the lumps of the registered version. 
		if (registered)
			for (i = 0; i < 23; i++)
				if (W_CheckNumForName(name[i]) < 0)
					I_Error("\nThis is not the registered version.");

	}

	// Iff additonal PWAD files are used, print modified banner
	if (modifiedgame) {
		getStringByIndex(MODIFIED_GAME, textbuffer);
		printf(textbuffer);
		getchar();
	}


#else

	// very weird. game crashes at startup if there is not a name array and a name check here. i dont see it used as an extern anywhere..
	if (0) {
		int8_t name[23][1] = { "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""};
		if (name[0]) {

		}

	}

#endif
 

#ifdef DEBUG_PRINTING
	if (registered) {
		getStringByIndex(VERSION_REGISTERED, textbuffer);
        printf(textbuffer);
		D_RedrawTitle();
		getStringByIndex(NOT_SHAREWARE, textbuffer);
		printf( textbuffer );
		D_RedrawTitle();
    }
    if (shareware) {
		getStringByIndex(VERSION_SHAREWARE, textbuffer);
        printf(textbuffer);
		D_RedrawTitle();
    }
    if (commercial) {
		getStringByIndex(VERSION_COMMERCIAL, textbuffer);
        printf(textbuffer);
		D_RedrawTitle();

		getStringByIndex(DO_NOT_DISTRIBUTE, textbuffer);
        printf( textbuffer );
		D_RedrawTitle();
    }

	getStringByIndex(M_INIT_TEXT, textbuffer);
	printf (textbuffer);
	D_RedrawTitle();
#endif
    M_Init ();

#ifdef DEBUG_PRINTING
	getStringByIndex(R_INIT_TEXT, textbuffer);
	printf(textbuffer);
	D_RedrawTitle();
#endif
    R_Init ();


#ifdef DEBUG_PRINTING
	getStringByIndex(P_INIT_TEXT, textbuffer);
	printf(textbuffer);
	D_RedrawTitle();
#endif
    P_Init ();


#ifdef DEBUG_PRINTING
	getStringByIndex(I_INIT_TEXT, textbuffer);
	printf(textbuffer);
	D_RedrawTitle();
#endif
    I_Init ();
	D_CheckNetGame ();

#ifdef DEBUG_PRINTING
	getStringByIndex(S_INIT_TEXT, textbuffer);
	printf(textbuffer);
	D_RedrawTitle();
#endif
    S_Init (sfxVolume*8, musicVolume*8);

#ifdef DEBUG_PRINTING
	getStringByIndex(HU_INIT_TEXT, textbuffer);
	printf(textbuffer);
	D_RedrawTitle();
#endif
    HU_Init ();

#ifdef DEBUG_PRINTING
	getStringByIndex(ST_INIT_TEXT, textbuffer);
	printf (textbuffer);
	D_RedrawTitle();
#endif
    ST_Init ();

    
    // start the apropriate game based on parms
    p = M_CheckParm ("-record");

    if (p && p < myargc-1)
    {
        G_RecordDemo (myargv[p+1]);
        autostart = true;
    }
        
    p = M_CheckParm ("-playdemo");
    if (p && p < myargc-1)
    {
        singledemo = true;              // quit after one demo
        G_DeferedPlayDemo (myargv[p+1]);
        D_DoomLoop ();  // never returns
    }
        
    p = M_CheckParm ("-timedemo");
    if (p && p < myargc-1)
    {
        G_TimeDemo (myargv[p+1]);
        D_DoomLoop ();  // never returns
    }
        
    p = M_CheckParm ("-loadgame");
    if (p && p < myargc-1)
    {
        sprintf(file, SAVEGAMENAME"%c.dsg",myargv[p+1][0]);
        G_LoadGame (file);
    }
        

    if ( gameaction != ga_loadgame )
    {
        if (autostart)
            G_InitNew (startskill, startepisode, startmap);
        else
            D_StartTitle ();                // start up intro loop

    }

    D_DoomLoop ();  // never returns
}
