//
// Copyright (C) 1993-1996 Id Software, Inc.
// Copyright (C) 2016-2017 Alexey Khokholov (Nuke.YKT)
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// DESCRIPTION:
//	Thing frame/state LUT,
//	generated by multigen utilitiy.
//	This one is the original DOOM version, preserved.
//

// Data.
#include "sounds.h"
#include "doomdef.h"

#include "info.h"

#include "p_mobj.h"



state_t	*states; 



int16_t getPainChance(uint8_t id){

	switch (id){

		case MT_PLAYER:
		case MT_BOSSBRAIN:
			return 255;
		case MT_POSSESSED:
		case MT_TROOP:
			return 200;
		case MT_SHOTGUY:
			return 170;
		case MT_VILE:
			return 10;
		case MT_UNDEAD:
			return 100;
		case MT_FATSO:
			return 80;
		case MT_CHAINGUY:
			return 170;
		case MT_SERGEANT:
		case MT_SHADOWS:
			return 180;
		case MT_HEAD:
			return 128;
		case MT_BRUISER:
		case MT_KNIGHT:
			return 50;
		case MT_SKULL:
		case MT_KEEN:
			return 256;
		case MT_SPIDER:
			return 40;
		case MT_BABY:
			return 128;
		case MT_CYBORG:
			return 20;
		case MT_PAIN:
			return 128;
		case MT_WOLFSS:
			return 170;
		default:
			return 0;
	}
}



int16_t getRaiseState(uint8_t id){

	switch (id){
		case MT_POSSESSED:
			return S_POSS_RAISE1;
		case MT_SHOTGUY:
			return S_SPOS_RAISE1;
		case MT_UNDEAD:
			return S_SKEL_RAISE1;
		case MT_FATSO:
			return S_FATT_RAISE1;
		case MT_CHAINGUY:
			return S_CPOS_RAISE1;
		case MT_TROOP:
			return S_TROO_RAISE1;
		case MT_SERGEANT:
		case MT_SHADOWS:
			return S_SARG_RAISE1;
		case MT_HEAD:
			return S_HEAD_RAISE1;
		case MT_BRUISER:
			return S_BOSS_RAISE1;
		case MT_KNIGHT:
			return S_BOS2_RAISE1;
		case MT_BABY:
			return S_BSPI_RAISE1;
		case MT_PAIN:
			return S_PAIN_RAISE1;
		case MT_WOLFSS:
			return S_SSWV_RAISE1;
		default:
			return S_NULL;
	}

}



int16_t getXDeathState(uint8_t id){

	switch (id){
		case MT_PLAYER:
			return S_PLAY_XDIE1;
		case MT_POSSESSED:
			return S_POSS_XDIE1;
		case MT_SHOTGUY:
			return S_SPOS_XDIE1;
		case MT_CHAINGUY:
			return S_CPOS_XDIE1;
		case MT_TROOP:
			return S_TROO_XDIE1;
		case MT_WOLFSS:
			return S_SSWV_XDIE1;
		default:
			return S_NULL;
	}

}

int16_t getMeleeState(uint8_t id){

	switch (id){
		case MT_UNDEAD:
			return S_SKEL_FIST1;
		case MT_TROOP:
			return S_TROO_ATK1;
		case MT_SERGEANT:
			return S_SARG_ATK1;
		case MT_SHADOWS:
			return S_SARG_ATK1;
		case MT_BRUISER:
			return S_BOSS_ATK1;
		case MT_KNIGHT:
			return S_BOS2_ATK1;
			default:
			return S_NULL;
	}

}



int32_t getMobjMass(uint8_t id){
	switch (id){

		case MT_SKULL:
			return 50;
		case MT_SERGEANT:
		case MT_SHADOWS:
		case MT_HEAD:
		case MT_PAIN:
			return 400;

		case MT_VILE:
		case MT_UNDEAD:
			return 500;
		case MT_BABY:
			return 600;
		case MT_FATSO:
		case MT_BRUISER:
		case MT_KNIGHT:
		case MT_SPIDER:
		case MT_CYBORG:
			return 1000;

		case MT_KEEN:
		case MT_BOSSBRAIN:
			return 10000000L;


		default:

			return 100;
	}
}

sfxenum_t getActiveSound(uint8_t id) {
	switch (id) {
		case 1:
		case 2:
		case 8:
		case 10:
		case 23:
			return sfx_posact;
		case 3:
			return sfx_vilact;
		case 5:
			return sfx_skeact;
		case 11:
			return sfx_bgact;
		case 12:
		case 13:
		case 14:
		case 15:
		case 17:
		case 18:
		case 19:
		case 21:
		case 22:
			return sfx_dmact;
		case 20:
			return sfx_bspact;
		default:
			return sfx_None;
	}
}

sfxenum_t getPainSound(uint8_t id) {
	switch (id) {
		case 0:
			return sfx_plpain;
		case 1:
		case 2:
		case 5:
		case 10:
		case 11:
		case 23:
			return sfx_popain;
		case 3:
			return sfx_vipain;
		case 8:
			return sfx_mnpain;

		case 12:
		case 13:
		case 14:
		case 15:

		case 17:
		case 18:
		case 19:
		case 20:
		case 21:
			return sfx_dmpain;

		case 22:
			return sfx_pepain;
		case 24:
			return sfx_keenpn;
		case 25:
			return sfx_bospn;
		default:
			return sfx_None;

	}
}





sfxenum_t getAttackSound(uint8_t id) {
	switch (id) {
	case 1:
		return sfx_pistol;
	case 12:
	case 13:
		return sfx_sgtatk;
		return sfx_sgtatk;
	case 17:
		return sfx_sklatk;
	case 18:
		return sfx_shotgn;
	default:
		return sfx_None;


	}
}


uint8_t getDamage(uint8_t id) {
	switch (id) {
	case 6:
		return 10;
	case 9:
	case 16:
		return 8;
		return 8;
	case 18:
	case 28:
	case 31:
		return 3;
	case 32:
	case 34:
	case 36:
		return 5;
	case 33:
		return 20;
	case 35:
		return 100;
	default:
		return 0;


	}
}

statenum_t getSeeState(uint8_t id) {
	switch (id) {
		case 0:
			return S_PLAY_RUN1;
		case 1:
			return S_POSS_RUN1;
		case 2:
			return S_SPOS_RUN1;
		case 3:
			return S_VILE_RUN1;
		case 5:
			return S_SKEL_RUN1;
		case 8:
			return S_FATT_RUN1;
		case 10:
			return S_CPOS_RUN1;
		case 11:
			return S_TROO_RUN1;
		case 12:
		case 13:
			return S_SARG_RUN1;
		case 14:
			return S_HEAD_RUN1;
		case 15:
			return S_BOSS_RUN1;
		case 17:
			return S_BOS2_RUN1;
		case 18:
			return S_SKULL_RUN1;
		case 19:
			return S_SPID_RUN1;
		case 20:
			return S_BSPI_SIGHT;
		case 21:
			return S_CYBER_RUN1;
		case 22:
			return S_PAIN_RUN1;
		case 23:
			return S_SSWV_RUN1;
		case 26:
			return S_BRAINEYESEE;
		default:
			return S_NULL;

	}
}


statenum_t getMissileState(uint8_t id) {
	switch (id) {

	case 0:
		return S_PLAY_ATK1;
	case 1:
		return S_POSS_ATK1;
	case 2:
		return S_SPOS_ATK1;
	case 3:
		return S_VILE_ATK1;
	case 5:
		return S_SKEL_MISS1;
	case 8:
		return S_FATT_ATK1;
	case 10:
		return S_CPOS_ATK1;
	case 11:
		return S_TROO_ATK1;
	case 14:
		return S_HEAD_ATK1;
	case 15:
		return S_BOSS_ATK1;
	case 17:
		return S_BOS2_ATK1;
	case 18:
		return S_SKULL_ATK1;
	case 19:
		return S_SPID_ATK1;
	case 20:
		return S_BSPI_ATK1;
	case 21:
		return S_CYBER_ATK1;
	case 22:
		return S_PAIN_ATK1;
	case 23:
		return S_SSWV_ATK1;
	default:
		return S_NULL;

	}
}



statenum_t getDeathState(uint8_t id) {
	switch (id) {


	case 0:
		return S_PLAY_DIE1;
	case 1:
		return S_POSS_DIE1;
	case 2:
		return S_SPOS_DIE1;
	case 3:
		return S_VILE_DIE1;
	case 5:
		return S_SKEL_DIE1;
	case 6:
		return S_TRACEEXP1;
	case 8:
		return S_FATT_DIE1;
	case 9:
		return S_FATSHOTX1;
	case 10:
		return S_CPOS_DIE1;
	case 11:
		return S_TROO_DIE1;
	case 12:
	case 13:
		return S_SARG_DIE1;
	case 14:
		return S_HEAD_DIE1;
	case 15:
		return S_BOSS_DIE1;
	case 16:
		return S_BRBALLX1;
	case 17:
		return S_BOS2_DIE1;
	case 18:
		return S_SKULL_DIE1;
	case 19:
		return S_SPID_DIE1;
	case 20:
		return S_BSPI_DIE1;
	case 21:
		return S_CYBER_DIE1;
	case 22:
		return S_PAIN_DIE1;
	case 23:
		return S_SSWV_DIE1;
	case 24:
		return S_COMMKEEN;
	case 25:
		return S_BRAIN_DIE1;
	case 30:
		return S_BEXP;
	case 31:
		return S_TBALLX1;
	case 32:
		return S_RBALLX1;
	case 33:
		return S_EXPLODE1;
	case 34:
		return S_PLASEXP;
	case 35:
		return S_BFGLAND;
	case 36:
		return S_ARACH_PLEX;
	default:
		return S_NULL;


	}
}



statenum_t getPainState(uint8_t id) {
	switch (id) {

		case 0:
			return S_PLAY_PAIN;
		case 1:
			return S_POSS_PAIN;
		case 2:
			return S_SPOS_PAIN;
		case 3:
			return S_VILE_PAIN;
		case 5:
			return S_SKEL_PAIN;
		case 8:
			return S_FATT_PAIN;
		case 10:
			return S_CPOS_PAIN;
		case 11:
			return S_TROO_PAIN;
		case 12:
		case 13:
			return S_SARG_PAIN;
		case 14:
			return S_HEAD_PAIN;
		case 15:
			return S_BOSS_PAIN;
		case 17:
			return S_BOS2_PAIN;
		case 18:
			return S_SKULL_PAIN;
		case 19:
			return S_SPID_PAIN;
		case 20:
			return S_BSPI_PAIN;
		case 21:
			return S_CYBER_PAIN;
		case 22:
			return S_PAIN_PAIN;
		case 23:
			return S_SSWV_PAIN;
		case 24:
			return S_KEENPAIN;
		case 25:
			return S_BRAIN_PAIN;
		default:
			return S_NULL;


	}
}


int16_t getSpawnHealth(uint8_t id) {
	switch (id) {
		case 0:
		case 18:
		case 24:
			return 100;
		case 1:
		case 30:
			return 20;
		case 2:
			return 30;
		case 3:
			return 700;
		case 4:
		case 6:
		case 7:
		case 9:
		case 15:
		case 16:
			return 1000;
		case 5:
			return 300;
		case 8:
			return 600;
		case 10:
			return 70;
		case 11:
			return 60;
		case 12:
		case 13:
			return 150;
		case 14:
		case 22:
			return 400;
		case 17:
		case 20:
			return 500;
		case 19:
			return 3000;
		case 21:
			return 4000;
		case 23:
			return 50;
		case 25:
			return 250;
		default:
			return 1000;

	}
}


// we have cut a lot of data out of here in various hacky ways. as long as it saves conventional memory,
// that should mean less paging and better performance. these fields are generally accessed infrequently
// anyway. conventional memory should be used on things being accessed all the time.

mobjinfo_t *mobjinfo;
