#define R_DrawColumnPrepOffset         0xB37
#define R_MapPlaneOffset               0x7D1
#define R_DrawFuzzColumnOffset         0x0
#define R_DrawSingleMaskedColumnOffset 0x137
#define R_DrawMaskedColumnOffset       0x1AD
#define R_DrawMaskedColumnSpriteOffset 0x0
#define R_DrawSkyColumnOffset          0x0
#define R_DrawSkyPlaneOffset           0x1C6

#define R_DrawColumnCodeSize           0xBA6
#define R_DrawSpanCodeSize             0x938
#define R_DrawFuzzColumnCodeSize       0x2AA
#define R_DrawMaskedColumnCodeSize     0xFD
#define R_DrawSkyColumnCodeSize        0x242
