#define R_DrawColumnPrepOffset         0xB37
#define R_MapPlaneOffset               0x7CA
#define R_DrawFuzzColumnOffset         0x0
#define R_DrawSingleMaskedColumnOffset 0x137
#define R_DrawMaskedColumnOffset       0x1B1
#define R_DrawMaskedColumnSpriteOffset 0x0
#define R_DrawSkyColumnOffset          0x0
#define R_DrawSkyPlaneOffset           0x7AF
#define R_DrawSkyPlaneDynamicOffset    0x73B

#define R_DrawColumnCodeSize           0xBA0
#define R_DrawSpanCodeSize             0x91A
#define R_DrawFuzzColumnCodeSize       0x2AA
#define R_DrawMaskedColumnCodeSize     0xF9
#define R_DrawSkyColumnCodeSize        0x832
